export const posts = [
  {
    uuid: "1post-01",
    title: "Macet berkepanjangan di jalur bypass lombok, lombok tengah menuju mataram",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto in, animi culpa doloribus delectus repellendus accusamus doloremque minus id? Ullam ea dolore reprehenderit enim libero quisquam, incidunt adipisci quaerat pariatur?",
    featuredImage: "https://picsum.photos/300/200",
    category: "News",
    author: "Admin",
  },
  {
    uuid: "2post-02",
    title: "Macet berkepanjangan di jalur bypass lombok, lombok tengah menuju mataram",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto in, animi culpa doloribus delectus repellendus accusamus doloremque minus id? Ullam ea dolore reprehenderit enim libero quisquam, incidunt adipisci quaerat pariatur?",
    featuredImage: "https://picsum.photos/300/200",
    category: "News",
    author: "Admin",
  },
  {
    uuid: "3post-03",
    title: "Macet berkepanjangan di jalur bypass lombok, lombok tengah menuju mataram",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto in, animi culpa doloribus delectus repellendus accusamus doloremque minus id? Ullam ea dolore reprehenderit enim libero quisquam, incidunt adipisci quaerat pariatur?",
    featuredImage: "https://picsum.photos/300/200",
    category: "News",
    author: "Admin",
  },
  {
    uuid: "4post-04",
    title: "Macet berkepanjangan di jalur bypass lombok, lombok tengah menuju mataram",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto in, animi culpa doloribus delectus repellendus accusamus doloremque minus id? Ullam ea dolore reprehenderit enim libero quisquam, incidunt adipisci quaerat pariatur?",
    featuredImage: "https://picsum.photos/300/200",
    category: "News",
    author: "Admin",
  },
  {
    uuid: "5post-05",
    title: "Macet berkepanjangan di jalur bypass lombok, lombok tengah menuju mataram",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto in, animi culpa doloribus delectus repellendus accusamus doloremque minus id? Ullam ea dolore reprehenderit enim libero quisquam, incidunt adipisci quaerat pariatur?",
    featuredImage: "https://picsum.photos/300/200",
    category: "News",
    author: "Admin",
  },
  {
    uuid: "6post-06",
    title: "Macet berkepanjangan di jalur bypass lombok, lombok tengah menuju mataram",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto in, animi culpa doloribus delectus repellendus accusamus doloremque minus id? Ullam ea dolore reprehenderit enim libero quisquam, incidunt adipisci quaerat pariatur?",
    featuredImage: "https://picsum.photos/300/200",
    category: "News",
    author: "Admin",
  }
]